import type { StateCode } from './regions.ts';

export type City = { id: string; name: string; stateId: StateCode; countryId: 'US'; population: number; populationRank: number; censusName: string; censusGeoid: string; sourceId: 'census' };
// Top 50 incorporated places, Census Vintage 2025, July 1 population.
// Consolidated city balances are used once, not duplicated with their counties.
export const cities: readonly City[] = [
  {
    "id": "us-36-51000",
    "name": "New York City",
    "stateId": "NY",
    "countryId": "US",
    "population": 8584629,
    "populationRank": 1,
    "censusName": "New York city",
    "censusGeoid": "3651000",
    "sourceId": "census"
  },
  {
    "id": "us-06-44000",
    "name": "Los Angeles",
    "stateId": "CA",
    "countryId": "US",
    "population": 3869089,
    "populationRank": 2,
    "censusName": "Los Angeles city",
    "censusGeoid": "0644000",
    "sourceId": "census"
  },
  {
    "id": "us-17-14000",
    "name": "Chicago",
    "stateId": "IL",
    "countryId": "US",
    "population": 2731585,
    "populationRank": 3,
    "censusName": "Chicago city",
    "censusGeoid": "1714000",
    "sourceId": "census"
  },
  {
    "id": "us-48-35000",
    "name": "Houston",
    "stateId": "TX",
    "countryId": "US",
    "population": 2397315,
    "populationRank": 4,
    "censusName": "Houston city",
    "censusGeoid": "4835000",
    "sourceId": "census"
  },
  {
    "id": "us-04-55000",
    "name": "Phoenix",
    "stateId": "AZ",
    "countryId": "US",
    "population": 1665481,
    "populationRank": 5,
    "censusName": "Phoenix city",
    "censusGeoid": "0455000",
    "sourceId": "census"
  },
  {
    "id": "us-42-60000",
    "name": "Philadelphia",
    "stateId": "PA",
    "countryId": "US",
    "population": 1574281,
    "populationRank": 6,
    "censusName": "Philadelphia city",
    "censusGeoid": "4260000",
    "sourceId": "census"
  },
  {
    "id": "us-48-65000",
    "name": "San Antonio",
    "stateId": "TX",
    "countryId": "US",
    "population": 1548422,
    "populationRank": 7,
    "censusName": "San Antonio city",
    "censusGeoid": "4865000",
    "sourceId": "census"
  },
  {
    "id": "us-06-66000",
    "name": "San Diego",
    "stateId": "CA",
    "countryId": "US",
    "population": 1406106,
    "populationRank": 8,
    "censusName": "San Diego city",
    "censusGeoid": "0666000",
    "sourceId": "census"
  },
  {
    "id": "us-48-19000",
    "name": "Dallas",
    "stateId": "TX",
    "countryId": "US",
    "population": 1329491,
    "populationRank": 9,
    "censusName": "Dallas city",
    "censusGeoid": "4819000",
    "sourceId": "census"
  },
  {
    "id": "us-48-27000",
    "name": "Fort Worth",
    "stateId": "TX",
    "countryId": "US",
    "population": 1028117,
    "populationRank": 10,
    "censusName": "Fort Worth city",
    "censusGeoid": "4827000",
    "sourceId": "census"
  },
  {
    "id": "us-12-35000",
    "name": "Jacksonville",
    "stateId": "FL",
    "countryId": "US",
    "population": 1017689,
    "populationRank": 11,
    "censusName": "Jacksonville city",
    "censusGeoid": "1235000",
    "sourceId": "census"
  },
  {
    "id": "us-48-05000",
    "name": "Austin",
    "stateId": "TX",
    "countryId": "US",
    "population": 1002632,
    "populationRank": 12,
    "censusName": "Austin city",
    "censusGeoid": "4805000",
    "sourceId": "census"
  },
  {
    "id": "us-06-68000",
    "name": "San Jose",
    "stateId": "CA",
    "countryId": "US",
    "population": 989814,
    "populationRank": 13,
    "censusName": "San Jose city",
    "censusGeoid": "0668000",
    "sourceId": "census"
  },
  {
    "id": "us-37-12000",
    "name": "Charlotte",
    "stateId": "NC",
    "countryId": "US",
    "population": 964784,
    "populationRank": 14,
    "censusName": "Charlotte city",
    "censusGeoid": "3712000",
    "sourceId": "census"
  },
  {
    "id": "us-39-18000",
    "name": "Columbus",
    "stateId": "OH",
    "countryId": "US",
    "population": 938396,
    "populationRank": 15,
    "censusName": "Columbus city",
    "censusGeoid": "3918000",
    "sourceId": "census"
  },
  {
    "id": "us-18-36003",
    "name": "Indianapolis",
    "stateId": "IN",
    "countryId": "US",
    "population": 901116,
    "populationRank": 16,
    "censusName": "Indianapolis city (balance)",
    "censusGeoid": "1836003",
    "sourceId": "census"
  },
  {
    "id": "us-06-67000",
    "name": "San Francisco",
    "stateId": "CA",
    "countryId": "US",
    "population": 826079,
    "populationRank": 17,
    "censusName": "San Francisco city",
    "censusGeoid": "0667000",
    "sourceId": "census"
  },
  {
    "id": "us-53-63000",
    "name": "Seattle",
    "stateId": "WA",
    "countryId": "US",
    "population": 784777,
    "populationRank": 18,
    "censusName": "Seattle city",
    "censusGeoid": "5363000",
    "sourceId": "census"
  },
  {
    "id": "us-08-20000",
    "name": "Denver",
    "stateId": "CO",
    "countryId": "US",
    "population": 740613,
    "populationRank": 19,
    "censusName": "Denver city",
    "censusGeoid": "0820000",
    "sourceId": "census"
  },
  {
    "id": "us-47-52006",
    "name": "Nashville",
    "stateId": "TN",
    "countryId": "US",
    "population": 721074,
    "populationRank": 20,
    "censusName": "Nashville-Davidson metropolitan government (balance)",
    "censusGeoid": "4752006",
    "sourceId": "census"
  },
  {
    "id": "us-40-55000",
    "name": "Oklahoma City",
    "stateId": "OK",
    "countryId": "US",
    "population": 719849,
    "populationRank": 21,
    "censusName": "Oklahoma City city",
    "censusGeoid": "4055000",
    "sourceId": "census"
  },
  {
    "id": "us-11-50000",
    "name": "Washington",
    "stateId": "DC",
    "countryId": "US",
    "population": 693645,
    "populationRank": 22,
    "censusName": "Washington city",
    "censusGeoid": "1150000",
    "sourceId": "census"
  },
  {
    "id": "us-48-24000",
    "name": "El Paso",
    "stateId": "TX",
    "countryId": "US",
    "population": 683012,
    "populationRank": 23,
    "censusName": "El Paso city",
    "censusGeoid": "4824000",
    "sourceId": "census"
  },
  {
    "id": "us-32-40000",
    "name": "Las Vegas",
    "stateId": "NV",
    "countryId": "US",
    "population": 679817,
    "populationRank": 24,
    "censusName": "Las Vegas city",
    "censusGeoid": "3240000",
    "sourceId": "census"
  },
  {
    "id": "us-25-07000",
    "name": "Boston",
    "stateId": "MA",
    "countryId": "US",
    "population": 672973,
    "populationRank": 25,
    "censusName": "Boston city",
    "censusGeoid": "2507000",
    "sourceId": "census"
  },
  {
    "id": "us-26-22000",
    "name": "Detroit",
    "stateId": "MI",
    "countryId": "US",
    "population": 649095,
    "populationRank": 26,
    "censusName": "Detroit city",
    "censusGeoid": "2622000",
    "sourceId": "census"
  },
  {
    "id": "us-21-48006",
    "name": "Louisville",
    "stateId": "KY",
    "countryId": "US",
    "population": 641962,
    "populationRank": 27,
    "censusName": "Louisville/Jefferson County metro government (balance)",
    "censusGeoid": "2148006",
    "sourceId": "census"
  },
  {
    "id": "us-41-59000",
    "name": "Portland",
    "stateId": "OR",
    "countryId": "US",
    "population": 635109,
    "populationRank": 28,
    "censusName": "Portland city",
    "censusGeoid": "4159000",
    "sourceId": "census"
  },
  {
    "id": "us-47-48000",
    "name": "Memphis",
    "stateId": "TN",
    "countryId": "US",
    "population": 609647,
    "populationRank": 29,
    "censusName": "Memphis city",
    "censusGeoid": "4748000",
    "sourceId": "census"
  },
  {
    "id": "us-24-04000",
    "name": "Baltimore",
    "stateId": "MD",
    "countryId": "US",
    "population": 569997,
    "populationRank": 30,
    "censusName": "Baltimore city",
    "censusGeoid": "2404000",
    "sourceId": "census"
  },
  {
    "id": "us-55-53000",
    "name": "Milwaukee",
    "stateId": "WI",
    "countryId": "US",
    "population": 562407,
    "populationRank": 31,
    "censusName": "Milwaukee city",
    "censusGeoid": "5553000",
    "sourceId": "census"
  },
  {
    "id": "us-35-02000",
    "name": "Albuquerque",
    "stateId": "NM",
    "countryId": "US",
    "population": 556588,
    "populationRank": 32,
    "censusName": "Albuquerque city",
    "censusGeoid": "3502000",
    "sourceId": "census"
  },
  {
    "id": "us-06-27000",
    "name": "Fresno",
    "stateId": "CA",
    "countryId": "US",
    "population": 555549,
    "populationRank": 33,
    "censusName": "Fresno city",
    "censusGeoid": "0627000",
    "sourceId": "census"
  },
  {
    "id": "us-04-77000",
    "name": "Tucson",
    "stateId": "AZ",
    "countryId": "US",
    "population": 548371,
    "populationRank": 34,
    "censusName": "Tucson city",
    "censusGeoid": "0477000",
    "sourceId": "census"
  },
  {
    "id": "us-06-64000",
    "name": "Sacramento",
    "stateId": "CA",
    "countryId": "US",
    "population": 536449,
    "populationRank": 35,
    "censusName": "Sacramento city",
    "censusGeoid": "0664000",
    "sourceId": "census"
  },
  {
    "id": "us-13-04000",
    "name": "Atlanta",
    "stateId": "GA",
    "countryId": "US",
    "population": 529110,
    "populationRank": 36,
    "censusName": "Atlanta city",
    "censusGeoid": "1304000",
    "sourceId": "census"
  },
  {
    "id": "us-29-38000",
    "name": "Kansas City",
    "stateId": "MO",
    "countryId": "US",
    "population": 521220,
    "populationRank": 37,
    "censusName": "Kansas City city",
    "censusGeoid": "2938000",
    "sourceId": "census"
  },
  {
    "id": "us-04-46000",
    "name": "Mesa",
    "stateId": "AZ",
    "countryId": "US",
    "population": 513656,
    "populationRank": 38,
    "censusName": "Mesa city",
    "censusGeoid": "0446000",
    "sourceId": "census"
  },
  {
    "id": "us-37-55000",
    "name": "Raleigh",
    "stateId": "NC",
    "countryId": "US",
    "population": 506306,
    "populationRank": 39,
    "censusName": "Raleigh city",
    "censusGeoid": "3755000",
    "sourceId": "census"
  },
  {
    "id": "us-08-16000",
    "name": "Colorado Springs",
    "stateId": "CO",
    "countryId": "US",
    "population": 494743,
    "populationRank": 40,
    "censusName": "Colorado Springs city",
    "censusGeoid": "0816000",
    "sourceId": "census"
  },
  {
    "id": "us-12-45000",
    "name": "Miami",
    "stateId": "FL",
    "countryId": "US",
    "population": 489812,
    "populationRank": 41,
    "censusName": "Miami city",
    "censusGeoid": "1245000",
    "sourceId": "census"
  },
  {
    "id": "us-31-37000",
    "name": "Omaha",
    "stateId": "NE",
    "countryId": "US",
    "population": 488797,
    "populationRank": 42,
    "censusName": "Omaha city",
    "censusGeoid": "3137000",
    "sourceId": "census"
  },
  {
    "id": "us-51-82000",
    "name": "Virginia Beach",
    "stateId": "VA",
    "countryId": "US",
    "population": 453737,
    "populationRank": 43,
    "censusName": "Virginia Beach city",
    "censusGeoid": "5182000",
    "sourceId": "census"
  },
  {
    "id": "us-06-43000",
    "name": "Long Beach",
    "stateId": "CA",
    "countryId": "US",
    "population": 450469,
    "populationRank": 44,
    "censusName": "Long Beach city",
    "censusGeoid": "0643000",
    "sourceId": "census"
  },
  {
    "id": "us-06-53000",
    "name": "Oakland",
    "stateId": "CA",
    "countryId": "US",
    "population": 440838,
    "populationRank": 45,
    "censusName": "Oakland city",
    "censusGeoid": "0653000",
    "sourceId": "census"
  },
  {
    "id": "us-27-43000",
    "name": "Minneapolis",
    "stateId": "MN",
    "countryId": "US",
    "population": 430324,
    "populationRank": 46,
    "censusName": "Minneapolis city",
    "censusGeoid": "2743000",
    "sourceId": "census"
  },
  {
    "id": "us-06-03526",
    "name": "Bakersfield",
    "stateId": "CA",
    "countryId": "US",
    "population": 422165,
    "populationRank": 47,
    "censusName": "Bakersfield city",
    "censusGeoid": "0603526",
    "sourceId": "census"
  },
  {
    "id": "us-40-75000",
    "name": "Tulsa",
    "stateId": "OK",
    "countryId": "US",
    "population": 416209,
    "populationRank": 48,
    "censusName": "Tulsa city",
    "censusGeoid": "4075000",
    "sourceId": "census"
  },
  {
    "id": "us-12-71000",
    "name": "Tampa",
    "stateId": "FL",
    "countryId": "US",
    "population": 413554,
    "populationRank": 49,
    "censusName": "Tampa city",
    "censusGeoid": "1271000",
    "sourceId": "census"
  },
  {
    "id": "us-08-04000",
    "name": "Aurora",
    "stateId": "CO",
    "countryId": "US",
    "population": 410053,
    "populationRank": 50,
    "censusName": "Aurora city",
    "censusGeoid": "0804000",
    "sourceId": "census"
  }
];

