import type { LifeEvent, Choice } from './data';
const choice = (label: string, outcome: string, effect: Choice['effect'], schoolEffect?: Choice['schoolEffect']): Choice => ({label,hint:'Shape your childhood.',outcome,effect,schoolEffect});
// Index equals age. Add new childhood scenarios here without changing the simulation.
export const childhoodEvents: LifeEvent[] = [
  {category:'Family',title:'Welcome to the world',text:'Your parents welcome you home. Your story is just beginning.',choices:[choice('Snuggle with my family','My parents welcomed me into the world with love.',{Happiness:3})]},
  {category:'Childhood',title:'My first words',text:'You are beginning to make yourself understood.',choices:[choice('Say a familiar word','I said one of my first words. My parents were delighted.',{Smarts:2,Happiness:2}),choice('Point and giggle','I pointed at everything that caught my eye.',{Happiness:3})]},
  {category:'Childhood',title:'Little explorer',text:'You can move around on your own, with a parent nearby.',choices:[choice('Explore the garden','I explored the garden with my parent.',{Health:2,Happiness:2}),choice('Build with blocks','I built a tower from colorful blocks.',{Smarts:3})]},
  {category:'Family',title:'Story time',text:'Your parent has time to read you a bedtime story.',choices:[choice('Ask lots of questions','I asked questions about our bedtime story.',{Smarts:3}),choice('Cuddle and listen','I cuddled with my parent and listened to a story.',{Happiness:3})]},
  {category:'Childhood',title:'A day at the playground',text:'Another child wants to play with you.',choices:[choice('Play together','I made a playground friend.',{Happiness:3}),choice('Try the climbing frame','I tried the climbing frame with my parent watching.',{Health:3})]},
  {category:'Childhood',title:'Getting ready for school',text:'Your family helps you practice for your first school year.',choices:[choice('Practice letters','I practiced my letters before starting school.',{Smarts:4}),choice('Practice sharing','I practiced sharing and taking turns.',{Happiness:3})]},
  {category:'Education',title:'My first day of school',text:'You have started elementary school. Your classroom is full of new faces.',choices:[choice('Introduce myself','I introduced myself on my first day of elementary school.',{Happiness:2},{popularity:4}),choice('Listen carefully','I listened carefully on my first day of elementary school.',{Smarts:2},{grades:4})]},
  {category:'Education',title:'A tricky homework question',text:'One of your homework questions is proving difficult.',choices:[choice('Ask a parent for help','My parent helped me understand my homework.',{Smarts:3},{grades:3}),choice('Try it myself','I worked through a difficult homework question.',{Smarts:2},{grades:2})]},
  {category:'Childhood',title:'Choosing a hobby',text:'You have a chance to try something after school.',choices:[choice('Play a sport','I tried a sport after school.',{Health:3,Happiness:2},{popularity:2}),choice('Make something creative','I made something creative after school.',{Smarts:3,Happiness:2})]},
  {category:'Education',title:'Someone sitting alone',text:'A classmate is sitting alone at lunchtime.',choices:[choice('Invite them to join me','I invited a lonely classmate to sit with me.',{Happiness:3},{popularity:4}),choice('Have a quiet lunch','I enjoyed a quiet lunch at school.',{Happiness:1})]},
  {category:'Education',title:'Starting middle school',text:'Elementary school is complete. You have started middle school with new classes and classmates.',choices:[choice('Focus on my classes','I started middle school and focused on my classes.',{Smarts:3},{grades:4}),choice('Get to know my classmates','I started middle school and got to know my classmates.',{Happiness:3},{popularity:4})]},
  {category:'Family',title:'Growing more independent',text:'Your parents offer you a little more responsibility at home.',choices:[choice('Help around the house','I helped my family around the house.',{Happiness:3}),choice('Learn to make a meal','My parent taught me how to make a simple meal.',{Smarts:3})]},
  {category:'Education',title:'The class presentation',text:'It is your turn to present a project to the class.',choices:[choice('Prepare carefully','I prepared carefully for my class presentation.',{Smarts:3},{grades:4}),choice('Present with confidence','I confidently presented my project to the class.',{Happiness:2},{popularity:3})]}
];
export function childhoodEvent(age: number): LifeEvent | undefined { return childhoodEvents[age]; }
