import type {WorkAction} from './partTimeWork';
import {playerEducation} from './profileDetails';
import {barColor} from './statBars';
import SchoolMemberships from './SchoolMemberships';
import type {MembershipAction} from './schoolCommitments';
import { Icon } from './ClassicUI';
import { getOccupation, schoolYear, schoolStage, schoolName, schoolActions, type SchoolAction } from './occupation';
import type { Life } from './saves';
import { money } from './money';

export function Meter({ name, value }: { name: string; value: number }) {
  return <div className="occupation-meter"><div><span>{name}</span></div><div className="relationship-meter" role="progressbar" aria-label={name} aria-valuenow={value} aria-valuemin={0} aria-valuemax={100}><div style={{width:`${value}%`,background:barColor(value)}}/></div></div>;
}
export function JobDetails({ life,onAction }: { life: Life;onAction?:(action:WorkAction)=>void }) {
  const job = getOccupation(life).job;
  return <><div className="directory-heading"><Icon kind="folder"/><div><h2>Job</h2><p>Your current employment.</p></div></div>{job ? <><fieldset className="occupation-details"><legend>Current position</legend><dl><div><dt>Position</dt><dd>{job.position}</dd></div><div><dt>Employer</dt><dd>{job.employer}</dd></div>{job.hourlyWage!==undefined?<><div><dt>Hourly wage</dt><dd>{money(job.hourlyWage)} USD</dd></div><div><dt>Weekly hours</dt><dd>{job.weeklyHours} hours</dd></div></>:<div><dt>Annual salary</dt><dd>{money(job.salary)} USD</dd></div>}<div><dt>Schedule</dt><dd>{job.hours}</dd></div><div><dt>Years in position</dt><dd>{life.age - job.startAge}</dd></div><div><dt>Started</dt><dd>Age {job.startAge}</dd></div></dl></fieldset><fieldset className="occupation-details"><legend>At work</legend><Meter name="Performance" value={job.performance}/>{job.hourlyWage!==undefined && <div className="contact-action-list work-actions">{(['Hours','Fewer hours','Raise','Resign','Work harder'] as WorkAction[]).map(action=><button key={action} onClick={()=>onAction?.(action)}><span className="interaction-emoji" aria-hidden="true">{({Hours:'⌛','Fewer hours':'⌛',Raise:'💸',Resign:'👋','Work harder':'💪'} as Record<WorkAction,string>)[action]}</span><span><strong>{action}</strong><small>{({Hours:'Request more hours','Fewer hours':'Request fewer hours',Raise:'Ask for a raise',Resign:'Tender your resignation','Work harder':'Put in some extra effort'} as Record<WorkAction,string>)[action]}</small></span><span>›</span></button>)}</div>}</fieldset></> : <div className="empty-folder"><Icon kind="folder"/><strong>You are not currently employed.</strong><p>{life.age < 14 ? 'Part-time jobs become available at age 14.' : 'Accepted job offers will appear here.'}</p><p>Full-time jobs become available after high school graduation.</p></div>}</>;
}
export function EducationDetails({ life, onAction,onMembership }: { life: Life; onMembership?:(id:string,action:MembershipAction,hours?:number)=>void; onAction: (action: SchoolAction) => void }) {
  const { school, highestEducation } = getOccupation(life);
  return <><div className="directory-heading"><Icon kind="document"/><div><h2>Education</h2><p>Your schooling and qualifications.</p></div></div><fieldset className="occupation-details"><legend>Qualifications</legend><dl><div><dt>Highest education</dt><dd>{highestEducation === 'None' ? playerEducation(life) : highestEducation === 'Secondary school' ? 'High school diploma' : highestEducation === 'Primary school' ? 'Elementary school' : highestEducation}</dd></div></dl></fieldset>{school ? <><fieldset className="occupation-details"><legend>Current school</legend><dl><div><dt>School</dt><dd>{schoolName(life,school)}</dd></div><div><dt>Level</dt><dd>{schoolStage(life,school)}</dd></div><div><dt>Class size</dt><dd>{(school.roster?.filter(person=>person.relation==='Classmate').length??0)+1} students</dd></div><div><dt>Principal</dt><dd>{school.roster?.find(person=>person.relation==='Principal')?.name??'—'}</dd></div><div><dt>Grade</dt><dd>{school.level === 'University' ? 'Undergraduate' : life.age - 5}</dd></div><div><dt>School year</dt><dd>Year {school.level === 'University' ? schoolYear(life,school) : schoolYear(life,school)} of {school.level === 'University' ? school.duration : school.duration}</dd></div><div><dt>Enrolled</dt><dd>Age {school.startAge}</dd></div></dl></fieldset><fieldset className="occupation-details"><legend>School life</legend><Meter name="Grades" value={school.grades}/><Meter name="Popularity" value={school.popularity}/><div className="contact-action-list school-actions">{(school.level==='University'?['Study harder'] as SchoolAction[]:schoolActions(life.age)).map(action => <button key={action} onClick={()=>onAction(action)}><span className="interaction-emoji" aria-hidden="true">{({'Change schools':'📖','Drop out':'👋',Nurse:'⚕️','Skip school':'🤫','Study harder':'📚','School dance':'💃'} as Record<string,string>)[action]}</span><span><strong>{action}</strong><small>{action==='Change schools'?'Ask to go to a different school':action==='Drop out'?`Drop out of ${school.level==='Primary school'?'elementary school':school.level==='Middle school'?'middle school':'high school'}`:action==='Nurse'?'Visit the school nurse':action==='Skip school'?'Skip class and do something else':action==='School dance'?'Attend a school dance':'Put in some extra effort'}</small></span><span>›</span></button>)}</div></fieldset>{school.memberships?.length ? <fieldset className="occupation-details"><legend>Current extracurriculars</legend><SchoolMemberships life={life} onAction={onMembership}/></fieldset>:null}</> : <div className="empty-folder"><Icon kind="document"/><strong>{life.age < 6 ? 'School has not started yet.' : 'You are not currently in school.'}</strong><p>{life.age < 6 ? 'Your first school year begins at age 6.' : 'Your completed education remains listed above.'}</p></div>}</>;
}

