import {barColor} from './statBars';
import {getOccupation} from './occupation';
import {schoolActivities,schoolActivityName} from './schoolActivityCatalog';
import {membershipInfo,membershipRank,type MembershipAction} from './schoolCommitments';
import type {Life} from './saves';
export default function SchoolMemberships({life,onAction}:{life:Life;onAction?:(id:string,action:MembershipAction,hours?:number)=>void}) {
 const school=getOccupation(life).school;if(!school?.memberships?.length)return null;
 return <div className="school-memberships">{schoolActivities.filter(a=>school.memberships!.includes(a.id)).sort((a,b)=>schoolActivityName(a,life.family?.gender).localeCompare(schoolActivityName(b,life.family?.gender))).map(activity=>{const detail=membershipInfo(school,activity.id,life.age);return <section className="membership-card" key={activity.id}><h3>{activity.emoji} {schoolActivityName(activity,life.family?.gender)}</h3><dl><div><dt>Membership</dt><dd>{membershipRank(activity.group,detail.rank)}</dd></div><div><dt>Years on {activity.group==='Sports'?'team':'club'}</dt><dd>{detail.years}</dd></div></dl><div className="membership-performance"><strong>Performance</strong><div className="relationship-meter" role="progressbar" aria-label={`${activity.name} Performance`} aria-valuenow={detail.performance} aria-valuemin={0} aria-valuemax={100}><div style={{width:`${detail.performance}%`,background:barColor(detail.performance)}}/></div></div><label className="membership-hours">Time Commitment · {detail.hours} hours/week<input type="range" min="1" max="10" step="1" value={detail.hours} aria-label={`${activity.name} weekly hours`} onChange={e=>onAction?.(activity.id,'Hours',Number(e.target.value))}/></label><div className="membership-actions"><button className="classic-button" onClick={()=>onAction?.(activity.id,'Train')}>{activity.group==='Sports'?'Practice harder':'Work harder'}</button><button className="classic-button" onClick={()=>onAction?.(activity.id,'Quit')}>{activity.group==='Sports'?'Quit the team':'Quit the club'}</button></div></section>;})}</div>;
}
