import {barColor} from './statBars';
import {useState} from 'react';
import {characters} from './relationships';
import {attractedTo} from './preferences';
import type {Life} from './saves';
import type {DanceMode,DanceOutcome} from './schoolDance';
export default function SchoolDancePanel({life,outcome,onResolve,onRetry,onClose}:{life:Life;outcome:DanceOutcome|null;onResolve:(mode:DanceMode,id?:string)=>void;onRetry:()=>void;onClose:()=>void}) {
 const [asking,setAsking]=useState<'classmate'|'friend'|false>(false),[selected,setSelected]=useState('');
 const partner=characters(life).personal.find(p=>p.status==='dating');
 const friends=characters(life).personal.filter(p=>!p.family&&p.friendship&&p.status!=='dating').sort((a,b)=>a.name.localeCompare(b.name));
 const classmates=characters(life).school.filter(p=>p.relation==='Classmate'&&attractedTo(life.sexuality??'Straight',life.family?.gender??'Male',p.gender)).sort((a,b)=>a.name.localeCompare(b.name));
 if(outcome)return <><div className="modal-content"><h2>School dance</h2><p className="event-description">{outcome.text}</p>{outcome.bars.map(bar=><div className="result-reaction" key={bar.label}><strong>{bar.label}</strong><div className="result-reaction-track" role="progressbar" aria-label={bar.label} aria-valuenow={bar.value} aria-valuemin={0} aria-valuemax={100}><div style={{width:`${bar.value}%`,background:barColor(bar.value)}}/></div></div>)}</div><div className="dialog-actions"><button className="classic-button" autoFocus onClick={()=>{if(outcome.retry){setAsking(false);onRetry();}else onClose();}}>{outcome.retry?'Back to dance options':'OK'}</button></div></>;
 return <><div className="modal-content" onKeyDown={e=>{if(e.key==='Escape' && asking){e.preventDefault();e.stopPropagation();setAsking(false);}}}><h2>💃 School dance</h2>{asking?<><p>Who would you like to invite?</p><label htmlFor="dance-classmate">{asking==='friend'?'Friend':'Classmate'}</label><select id="dance-classmate" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Choose a {asking==='friend'?'friend':'classmate'}</option>{(asking==='friend'?friends:classmates).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><div className="event-choices"><button className="classic-button choice-button" disabled={!selected} onClick={()=>onResolve(asking==='friend'?'friends':'classmate',selected)}>Work up my courage</button><button className="classic-button choice-button" onClick={()=>onResolve('alone')}>Nevermind, I'll go alone</button><button className="classic-button choice-button" onClick={()=>{setSelected('');setAsking('friend');}}>Nevermind, I'll go with a friend</button></div></>:<div className="event-choices">{partner?<button className="classic-button choice-button" onClick={()=>onResolve('partner')}>I'll go with my {partner.gender==='Female'?'girlfriend':'boyfriend'}</button>:<button className="classic-button choice-button" onClick={()=>{setSelected('');setAsking('classmate');}}>Ask out a classmate</button>}<button className="classic-button choice-button" onClick={()=>{setSelected('');setAsking('friend');}}>Go with a friend</button><button className="classic-button choice-button" onClick={()=>onResolve('alone')}>Go alone</button></div>}</div><div className="dialog-actions">{asking && <button className="classic-button" onClick={()=>setAsking(false)}>Back</button>}<button className="classic-button" onClick={onClose}>Nevermind</button></div></>;
}
