export const schoolActivities=[
{"id": "cooking", "name": "Cooking club", "group": "Clubs", "emoji": "🍳", "description": "Explore cooking with other students."},
{"id": "film", "name": "Film club", "group": "Clubs", "emoji": "🎬", "description": "Explore film with other students."},
{"id": "foreign-language", "name": "Foreign Language club", "group": "Clubs", "emoji": "🌎", "description": "Explore foreign language with other students."},
{"id": "photography", "name": "Photography club", "group": "Clubs", "emoji": "📷", "description": "Explore photography with other students."},
{"id": "robotics", "name": "Robotics club", "group": "Clubs", "emoji": "🤖", "description": "Explore robotics with other students."},
{"id": "chess", "name": "Chess club", "group": "Clubs", "emoji": "♟️", "description": "Explore chess with other students."},
{"id": "book", "name": "Book club", "group": "Clubs", "emoji": "📚", "description": "Explore book with other students."},
{"id": "history", "name": "History club", "group": "Clubs", "emoji": "🏛️", "description": "Explore history with other students."},
{"id": "student-council", "name": "Student Council", "group": "Clubs", "emoji": "🗳️", "description": "Explore student council with other students."},
{"id": "debate", "name": "Speech and Debate club", "group": "Clubs", "emoji": "🎤", "description": "Explore speech and debate with other students."},
{"id": "math", "name": "Math club", "group": "Clubs", "emoji": "➗", "description": "Explore math with other students."},
{"id": "science", "name": "Science club", "group": "Clubs", "emoji": "🔬", "description": "Explore science with other students."},
{"id": "business", "name": "Business club", "group": "Clubs", "emoji": "💼", "description": "Explore business with other students."},
{"id": "honor-society", "name": "Honor Society", "group": "Clubs", "emoji": "🎖️", "description": "Explore honor society with other students."},
{"id": "politics", "name": "Politics club", "group": "Clubs", "emoji": "🏛️", "description": "Explore politics with other students."},
{"id": "video-games", "name": "Video Games club", "group": "Clubs", "emoji": "🎮", "description": "Explore video games with other students."},
{"id": "art", "name": "Art club", "group": "Clubs", "emoji": "🎨", "description": "Explore art with other students."},
{"id": "badminton", "name": "Badminton team", "group": "Sports", "emoji": "🏸", "description": "Try out for the school badminton team."},
{"id": "baseball", "name": "Baseball team", "group": "Sports", "emoji": "⚾", "description": "Try out for the school baseball team."},
{"id": "basketball", "name": "Basketball team", "group": "Sports", "emoji": "🏀", "description": "Try out for the school basketball team."},
{"id": "cheerleading", "name": "Cheerleading team", "group": "Sports", "emoji": "📣", "description": "Try out for the school cheerleading team."},
{"id": "diving", "name": "Diving team", "group": "Sports", "emoji": "🤿", "description": "Try out for the school diving team."},
{"id": "football", "name": "Football team", "group": "Sports", "emoji": "🏈", "description": "Try out for the school football team."},
{"id": "golf", "name": "Golf team", "group": "Sports", "emoji": "⛳", "description": "Try out for the school golf team."},
{"id": "gymnastics", "name": "Gymnastics team", "group": "Sports", "emoji": "🤸", "description": "Try out for the school gymnastics team."},
{"id": "hockey", "name": "Hockey team", "group": "Sports", "emoji": "🏒", "description": "Try out for the school hockey team."},
{"id": "lacrosse", "name": "Lacrosse team", "group": "Sports", "emoji": "🥍", "description": "Try out for the school lacrosse team."},
{"id": "rugby", "name": "Rugby team", "group": "Sports", "emoji": "🏉", "description": "Try out for the school rugby team."},
{"id": "soccer", "name": "Soccer team", "group": "Sports", "emoji": "⚽", "description": "Try out for the school soccer team."},
{"id": "swimming", "name": "Swim team", "group": "Sports", "emoji": "🏊", "description": "Try out for the school swim team."},
{"id": "tennis", "name": "Tennis team", "group": "Sports", "emoji": "🎾", "description": "Try out for the school tennis team."},
{"id": "track", "name": "Track team", "group": "Sports", "emoji": "🏃", "description": "Try out for the school track team."},
{"id": "volleyball", "name": "Volleyball team", "group": "Sports", "emoji": "🏐", "description": "Try out for the school volleyball team."},
{"id": "wrestling", "name": "Wrestling team", "group": "Sports", "emoji": "🤼", "description": "Try out for the school wrestling team."}
,
{id:"drama",name:"Drama club",group:"Clubs",emoji:"🎭",description:"Explore drama with classmates."},
{id:"music",name:"Music club",group:"Clubs",emoji:"🎵",description:"Explore music with classmates."},
{id:"yearbook",name:"Yearbook club",group:"Clubs",emoji:"📖",description:"Explore yearbook with classmates."},
{id:"environmental",name:"Environmental club",group:"Clubs",emoji:"🌱",description:"Explore environmental with classmates."}] as const;
export function schoolActivityName(activity:typeof schoolActivities[number],gender?:string){return activity.id==='baseball' && gender==='Female'?'Softball team':activity.name;}
